---
title: "RWorksheet_Leysa#3b"
author: "Camilo Leysa"
date: "2024-10-01"
output: pdf_document
---

#Problem 1#
a.
```{r}
tabdata <- data.frame(Respondents=1:20, Sex= c(2,2,1,2,2,2,2,2,2,1,1,2,1,2,2,2,1,2,2,1),Fathers_Occupation=c(1,3,3,3,1,2,3,1,1,1,3,2,1,3,3,1,3,1,2,1),Persons_at_Home= c(5,7,3,8,5,9,6,7,8,4,7,5,4,7,8,8,3,11,7,6), Siblings_at_School=c(6,4,4,1,2,1,5,3,1,2,3,2,5,5,2,1,2,5,3,2), Types_of_Houses = c(1,2,3,1,1,3,3,1,2,3,2,3,2,2,3,3,3,3,3,2))
tabdata
```
b.
```{r}
str(tabdata)
summary(tabdata)
```
c.
```{r}
mean_sibling <- mean(c(6,4,4,1,2,1,5,3,1,2,3,2,5,5,2,1,2,5,3,2))
mean_sibling
```
d.
```{r}
first_two <- tabdata[1:2,]
first_two
```
e.
```{r}
sub_table <- tabdata[c(3,5), c(2,4)]
sub_table
```
f.
```{r}
types_houses <- tabdata$Types_of_Houses
types_houses
```
g.
```{r}
female_students <- tabdata[tabdata$Sex == 2 & tabdata$Siblings_at_School >=5,]
female_students
```

#Problem 2#
a.
```{r}
df = data.frame(Ints=integer(), Doubles=double(),Characters=character(), Logicals=logical(), Factors=factor(), stringsAsFactors=FALSE)
print("Structure of the empty dataframe: ")
print(str(df))
```
#Problem 3#
a.
```{r}
hdata <- read.csv("HouseholdData.csv")
hdata
```
b.
```{r}
hdata$Sex <- factor(hdata$Sex,levels = c("Male","Female"), labels=c(1,2))
hdata$Sex
```
c.
```{r}
hdata$Types.of.Houses <- factor(hdata$Types.of.Houses, levels = c("Wood","Congrete","Semi-congrete"), labels = c(1,2,3))
hdata$Types.of.Houses
```
d.
```{r}
hdata$Fathers.Occupation <- factor(hdata$Fathers.Occupation, levels = c("Farmer","Driver","Others"), labels = c(1,2,3))
hdata$Fathers.Occupation
```
e.
```{r}
rfemale <- subset(hdata, Sex ==2 & Fathers.Occupation==2)
rfemale
```

f.
```{r}
fildata <- subset(hdata,Siblings.at.School >=5)
fildata
```












