---
title: "RWorksheet_Leysa#1"
author: "Camilo Leysa"
date: "2024-09-20"
output: pdf_document
---
#Problem 1#

age <- c(34,28,22,36,27,18,52,39,42,29,35,31,27,22,37,34,19,20,57,49,50,37,46,25,17,37,42,53,41,51,35,24,33,41)
age_data_points <- length(age)
print(age)
print(age_data_points)

#Problem 2#

reciprocal_age <- 1/age
print(reciprocal_age)

#Problem 3#

new_age <- c(age, 0, age)
print(new_age)

#Problem 4#

sorted_age <- sort(age)
print(sorted_age)

#Problem 5#

min_age <- min(age)
max_age <- max(age)
print(min_age)
print(max_age)

#Problem 6#
data <- c(2.4,2.8,2.1,2.5,2.4,2.2,2.5,2.3,2.5,2.3,2.4,2.7)
data_data_points <- length(data)
print(data)
print(data_data_points)

#Problem 7#

data_double <- data*2
print(data_double)

#Problem 8.1#

integers_to_100 <- 1:100
print(integers_to_100)
int_100_data_points <- length(integers_to_100)
print(int_100_data_points)

#Problem 8.2#

numbers <- 20:60
print(numbers)
numbers_data_points <- length(numbers)
print  (numbers_data_points)

#Problem 8.3#

mean_num <- mean(numbers)
print(mean_num)
mean_num_data_points <- length(mean_num)
print(mean_num_data_points)

#Problem 8.4#

sum_num <- sum(51:91)
print(sum_num)
sum_data_points <- length(sum)
print(sum_data_points)

#Problem 8.5#

int_to_1k <- 1:1000
max_data_points <- max(int_to_1k[int_to_1k <= 10])
print(max_data_points)

#Problem 9#

Filter(function(i) {all(i%% c(3,5,7) !=0)}, seq(100))

#Problem 10#

backward_seq <- seq(100,1)
print(backward_seq)

#Problem 11#

multiples_new <- which((1:24) %% 3==0 | (1:24) %% 5==0)
print(multiples_new)
sum_multiple <- sum(multiples_new)
print(sum_multiple)

#Problem 12#

#x <- {0 + x + 5 + } (The code does not work)#

#Problem 13#

score <- c(72, 86, 92, 63, 88, 89, 91, 92, 75, 75, 77)
x2<- score[2]
x3 <- score[3]
print(x2)
print(x3)

#Problem 14#

a <- c(1,2,NA,4,NA,6,7)
print(a)
print(a, na.print="-999")

#Problem 15#

name = readline(prompt= "Input your Name: ")
age = readline(prompt="Input your age: ")
print(paste("My name is ",name,"and I am",age,"years old."))
print(R.version.string)
