---
title: "RWorksheet_Leysa#2"
author: "Camilo Leysa"
date: "2024-09-25"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Problem 1#
a.
```{r}
Sequence <- -5:5
print(Sequence)
```
b.
```{r}
x <-1:7
print(x)
```
#Problem 2#
```{r}
seq_function <-seq(1,3, by=0.2)
print(seq_function)
```
#Problem 3#
a.
```{r}
workers_age <- c(34,28,22,36,27,18,52,39,42,29,35,31,27,22,37,34,19,20,57,49,50,37,46,25,17,37,43,53,41,51,35,24,33,41,53,40,18,44,38,41,48,27,39,19,30,61,54,58,26,18)
print(workers_age)
third <- workers_age[3]
print(third)
```
b.
```{r}
second_and_fourth <- workers_age[c(2,4)]
print(second_and_fourth)
```
c.
```{r}
access_all <- workers_age[-c(4,12)]
print(access_all)
```
#Problem 4#
a.
```{r}
x <- c("first"=3, "second"=0, "third"=9)
names(x)
print(x)
result <- x[c("first", "third")]
print(result)
```
#Problem 5#
```{r}
x <- -3:2
x[2] <- 0
x
```
#Problem 6#
a.
```{r}
months <- c("Jan", "Feb", "March", "Apr", "May", "June")
price_per_liter <- c(52.50,57.25,60.00,65.00,74.25, 54.00)
purchase_quantity_Liters<- c(25,30,40,50,10,45)
data_frame_diesel <-data.frame(Month=months,
Price_per_Liter=price_per_liter,
Purchase_Quantity_Liters= purchase_quantity_Liters)
print(data_frame_diesel)
```
b.
```{r}
weighted.mean(purchase_quantity_Liters)
```
#Problem 7#
a.
```{r}
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers), sd(rivers), min(rivers), max(rivers))
data 
```
#Problem 8#
a.
```{r}
celebrity_ranking<-data.frame(Power_Ranking= c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25),
 Celebrity_Name= c("Tom Cruise", "Rolling Stones", "Oprah Winfrey", "U2", "Tiger Woods", "Steven Spielberg", "Howard Stern", "50 Cent", "Cast of the Sopranos", "Dan Brown", "Bruce Springsteen", "Donald Trump", "Muhammad Ali", "Paul McCartney", "George Lucas", "Elton John", "David Letterman", "Phil Mickelson", "J.K Rowling", "Bradd Pitt", "Peter Jackson", "Dr. Phil McGraw", "Jay Lenon", "Celine Dion", "Kobe Bryant"),

Pay= c(67,90,225,110,90,332,302,41,52,88,55,44,55,40,233,34,40,47,75,25,39,45,32,40,31))
celebrity_ranking
```
b.
```{r}
celebrity_ranking[celebrity_ranking$Celebrity_Name == "J.K Rowling", c("Power_Ranking", "Pay")] <- c(15, 90)
print(celebrity_ranking)
```
c.
```{r}
ranked_data <- read.csv("PowerRanking.csv")
print(ranked_data)
```
d.
```{r}
rows <- ranked_data[10:20,]
save(rows, file = "Ranks.RData")
print(rows)

```

#Problem 9#
a.
```{r}
library(openxlsx)
hotels_data <- read.xlsx("hotels-vienna.xlsx")
hotels_data
```
b.
```{r}
dim(hotels_data)
```
c.
```{r}
selected_dataset <- hotels_data[,c("country", "neighbourhood", "price", "stars", "accommodation_type", "rating")]
selected_dataset
```
d.
```{r}
save(selected_dataset, file = "new.RData")
load("new.RData")
```
e.
```{r}
head(selected_dataset)
tail(selected_dataset)
```
#Problem 10#
a.
```{r}
vegetables <- c("Carrot", "Onion", "Garlic", "Eggplant", "Potato", "Lettuce", "Squash", "Cabbage", "Ampalaya", "Pumpkin")

```
b.
```{r}
vegetables <- c(vegetables, "Okra", "Spinach")
vegetables
length(vegetables)

```
c. 
```{r}
added_veg <- append(vegetables, c("Peas", "Bamboo Shoots", "Seaweed", "Cucumber") , after=5)
added_veg
length(added_veg)

```
d.
```{r}
remove_veg <- added_veg[-c(5,10,15)]
remove_veg
length(remove_veg)

```